cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "git"
brew "mas"
brew "tig"
brew "vim"

cask "alfred"
cask "cheatsheet"
cask *google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "scroll-reverser"
cask "shiftit"
cask "visual-studio-code"

brew "docker"
cask "docker"
